name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: "mta_goservice"
  REGISTRY: "registry.digitalocean.com/mta-times"
    

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: Build the Docker image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest .
        
      - name: install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
        
#       - name: Remove old registry manifest
#         run: doctl registry repository delete-manifest mta_goservice 
#       - name: Remove old image
#         run: doctl registry repository dt -v mta_goservice latest
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
        
         
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEYTWO }}
          env: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # cd into directory
              cd ~/dev/mta
            # Stop Container 
              docker compose down 
            # Remove old container
              docker image rm $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
            # Restart container
              docker compose up -d 

 
 




